name: Bitkub Trading Bot

on:
  schedule:
    - cron: '*/30 * * * *' # Run every 5 minutes
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install
      
    - name: Run Bot
      env:
        BITKUB_API_KEY: ${{ secrets.API_KEY }}
        BITKUB_API_SECRET: ${{ secrets.API_SECRET }}
        TRADE_SYMBOL: THB_DOGE
        BUY_DIP_PERCENT: 2
        SELL_GAIN_PERCENT: 3
        TRADE_AMOUNT: 50
      run: npm start
