name: Bitkub Trading Bot

on:
  schedule:
    - cron: '0 * * * *' # ทุก 1 ชั่วโมง
  workflow_dispatch: # กดรันเองได้

jobs:
  trade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run trading bot
        env:
          BITKUB_API_KEY: ${{ secrets.BITKUB_API_KEY }}
          BITKUB_API_SECRET: ${{ secrets.BITKUB_API_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node index.js
